# Generated by Django 3.2.3 on 2021-05-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20210527_1921'),
        ('documento', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario'),
            preserve_default=False,
        ),
    ]
